export const US_STATES: { code: string; name: string }[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'Washington D.C.' },
]

// National chains available in all states
const NATIONAL_CHAINS = [
  'CVS Pharmacy',
  'Walgreens',
  'Walmart Pharmacy',
  'Costco Pharmacy',
  "Sam's Club Pharmacy",
  'Rite Aid',
  'Kroger Pharmacy',
  'Publix Pharmacy',
  'H-E-B Pharmacy',
  'Target Pharmacy (CVS)',
  'Albertsons Pharmacy',
  'Safeway Pharmacy',
  'Meijer Pharmacy',
  'Giant Eagle Pharmacy',
  'Winn-Dixie Pharmacy',
]

// Regional chains by state code
const STATE_CHAINS: Record<string, string[]> = {
  AL: ['Bruno\'s Pharmacy', 'Winn-Dixie Pharmacy', 'Harco Drug'],
  AK: ['Carrs Pharmacy', 'Fred Meyer Pharmacy'],
  AZ: ['Bashas\' Pharmacy', 'Fry\'s Food & Drug Pharmacy', 'AJ\'s Fine Foods Pharmacy'],
  AR: ['Harp\'s Food Stores Pharmacy', 'Harps Pharmacy'],
  CA: ['Longs Drugs', 'Raley\'s Pharmacy', 'Vons Pharmacy', 'Stater Bros. Pharmacy', 'Lucky Pharmacy', 'Pavilions Pharmacy'],
  CO: ['King Soopers Pharmacy', 'City Market Pharmacy', 'Natural Grocers Pharmacy'],
  CT: ['Stop & Shop Pharmacy', 'Big Y Pharmacy', 'Stop and Shop Pharmacy'],
  DE: ['Acme Pharmacy', 'ShopRite Pharmacy'],
  FL: ['Winn-Dixie Pharmacy', 'Navarro Discount Pharmacy', 'Presidente Supermarket Pharmacy'],
  GA: ['Ingles Pharmacy', 'Winn-Dixie Pharmacy', 'Kroger Pharmacy'],
  HI: ['Times Supermarket Pharmacy', 'Foodland Pharmacy', 'Longs Drugs'],
  ID: ['Albertsons Pharmacy', 'Fred Meyer Pharmacy', 'Rosauers Pharmacy'],
  IL: ['Jewel-Osco Pharmacy', 'Mariano\'s Pharmacy', 'Dominick\'s Pharmacy'],
  IN: ['Marsh Pharmacy', 'Martin\'s Super Markets Pharmacy'],
  IA: ['Hy-Vee Pharmacy', 'Fareway Pharmacy'],
  KS: ['Dillons Pharmacy', 'Price Chopper Pharmacy'],
  KY: ['Kroger Pharmacy', 'Pic-Pac Pharmacy'],
  LA: ['Rouse\'s Pharmacy', 'Winn-Dixie Pharmacy', 'Brookshire Pharmacy'],
  ME: ['Hannaford Pharmacy', 'Shaw\'s Pharmacy'],
  MD: ['Giant Pharmacy', 'Harris Teeter Pharmacy', 'Shoppers Food & Pharmacy'],
  MA: ['Stop & Shop Pharmacy', 'Market Basket Pharmacy', 'Hannaford Pharmacy'],
  MI: ['Meijer Pharmacy', 'Spartan Pharmacy', 'D&W Pharmacy'],
  MN: ['Cub Foods Pharmacy', 'Hy-Vee Pharmacy', 'Coborn\'s Pharmacy'],
  MS: ['Winn-Dixie Pharmacy', 'Piggly Wiggly Pharmacy'],
  MO: ['Schnucks Pharmacy', 'Dierbergs Pharmacy', 'Price Chopper Pharmacy'],
  MT: ['Rosauers Pharmacy', 'Town & Country Foods Pharmacy'],
  NE: ['Hy-Vee Pharmacy', 'Baker\'s Pharmacy'],
  NV: ['Smith\'s Pharmacy', 'Raley\'s Pharmacy'],
  NH: ['Hannaford Pharmacy', 'Shaw\'s Pharmacy', 'Market Basket Pharmacy'],
  NJ: ['ShopRite Pharmacy', 'Stop & Shop Pharmacy', 'Acme Pharmacy', 'Pathmark Pharmacy'],
  NM: ['Smith\'s Pharmacy', 'Lowe\'s Market Pharmacy'],
  NY: ['Duane Reade', 'ShopRite Pharmacy', 'Stop & Shop Pharmacy', 'Wegmans Pharmacy', 'Price Chopper Pharmacy'],
  NC: ['Harris Teeter Pharmacy', 'Food Lion Pharmacy', 'Ingles Pharmacy', 'Lowes Foods Pharmacy'],
  ND: ['Hugo\'s Pharmacy', 'Hornbacher\'s Pharmacy'],
  OH: ['Giant Eagle Pharmacy', 'Kroger Pharmacy', 'Marc\'s Pharmacy'],
  OK: ['Homeland Pharmacy', 'Reasor\'s Pharmacy'],
  OR: ['Fred Meyer Pharmacy', 'New Seasons Market Pharmacy', 'Grocery Outlet Pharmacy'],
  PA: ['Giant Pharmacy', 'Giant Eagle Pharmacy', 'Wegmans Pharmacy', 'Weis Markets Pharmacy', 'Redner\'s Pharmacy'],
  RI: ['Stop & Shop Pharmacy', 'Dave\'s Fresh Marketplace Pharmacy'],
  SC: ['Bi-Lo Pharmacy', 'Ingles Pharmacy', 'Harris Teeter Pharmacy'],
  SD: ['Hy-Vee Pharmacy', 'Lewis Drug'],
  TN: ['Kroger Pharmacy', 'Ingles Pharmacy', 'Food City Pharmacy'],
  TX: ['H-E-B Pharmacy', 'Brookshire\'s Pharmacy', 'Brookshire Brothers Pharmacy', 'Market Street Pharmacy', 'Randalls Pharmacy'],
  UT: ['Smith\'s Pharmacy', 'Harmons Pharmacy'],
  VT: ['Hannaford Pharmacy', 'Shaw\'s Pharmacy'],
  VA: ['Harris Teeter Pharmacy', 'Food Lion Pharmacy', 'Farm Fresh Pharmacy', 'Martin\'s Pharmacy'],
  WA: ['Fred Meyer Pharmacy', 'QFC Pharmacy', 'Bartell Drugs', 'Rosauers Pharmacy'],
  WV: ['Kroger Pharmacy', 'Tudor\'s Pharmacy'],
  WI: ['Pick \'n Save Pharmacy', 'Copps Pharmacy', 'Festival Foods Pharmacy'],
  WY: ['Albertsons Pharmacy', 'Town & Country Foods Pharmacy'],
  DC: ['Giant Pharmacy', 'Safeway Pharmacy'],
}

export function getPharmaciesForState(stateCode: string): string[] {
  const regional = STATE_CHAINS[stateCode] ?? []
  return [...new Set([...NATIONAL_CHAINS, ...regional])].sort()
}

export function getAllPharmacies(): string[] {
  const all = new Set<string>(NATIONAL_CHAINS)
  for (const chains of Object.values(STATE_CHAINS)) {
    for (const c of chains) all.add(c)
  }
  return [...all].sort()
}
